---
title: "COVID-19 - The big picture so far...."
date: "2020-08-15"
excerpt: "COVID-19 - The big picture so far...."
bibliography: ["../../static/bib/aviation.bib"]
link-citations: true
dwnld_i: <i class="fa pru fa-download"></i>
---
```{r echo = FALSE, message = FALSE, warning = FALSE}
# run setup script
source(here::here("_common.R"))
```
<style type="text/css">
.img-responsive {
    margin: 0 auto;
    max-width: 75%
}

.resp-container {
    position: relative;
    overflow: hidden;
    padding-top: 60.0%;
}

.resp-iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 150%;
    border: 0;
}
</style>

<small><p style="color:#808080">Published: 15 August 2020</p></small>

<div class="resp-container">
<iframe class="resp-iframe" src="https://datastudio.google.com/embed/reporting/5765cfaa-85a2-45e3-9890-8000c17cbe09/page/nTTw" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
#### The Big Picture
**Traffic:** Despite the continuous increase since mid-April 2020, there were a total of 3.47 million fewer flights in the EUROCONTROL Member States compared to the first seven months in 2019 (-54.5% vs. 2019). Focusing on the period May to July, traffic in 2020 was even -74.7% below 2019 levels. <br>
[More detailed information on the COVID-19 impact by State, Air Navigation Service Provider, ACC or airport](/covid/covid_traffic/)

**Charges:** As a consequence of the unprecedented reduction of traffic, revenues from en-route charges between January and July 2020 were -57.0% lower than planned which corresponds to a 2.67 billion Euro loss in the first seven months of 2020. <br>
[Explore revenues by Charging Zone](/covid/covid_ert_rev/)

**Delays:** As can be expected, ATFM en-route delays dropped to zero following the dramatic reduction in traffic in mid-April. Compared to the unacceptably high delays observed in 2019, en-route delays decreased by 84.6% which corresponds to 8.77 million minutes less delay. <br>
[See more information on ATFM delays by entity and delays cause](/capacity/)

#### Road to recovery
The rate of recovery is in line with the [EUROCONTROL "Coordinated Measures" Scenario][ectl_traff] which envisaged around 38% of the 2019 traffic level by the end of July. 

The latest [European NOP 2020 Recovery Plan][NOP_rec] expects to reach close to 60% of the 2019 traffic levels on peak days in September. However, this outlook is highly dependent on the evolution of State restrictions.

See [EUROCONTROLS latest comprehensive assessment][ectl_comp] of COVID’s impact on European traffic for frequent situation updates. 



[ectl_comp]: https://www.eurocontrol.int/publication/eurocontrol-comprehensive-assessment-covid-19s-impact-european-air-traffic "EUROCONTROLS comprehensive assessment"

[NOP_rec]: https://www.public.nm.eurocontrol.int/PUBPORTAL/gateway/spec/index.html "NOP Recovery Plan"

[ectl_traff]: https://www.eurocontrol.int/covid19#traffic-scenarios "Traffic scenarios"