---
title: "Technical Note - PRC trial with ANSPs to improve transparency in ATFCM operations"
type: "ATFM delay codes, Transparency, Operations, Capacity"
date: '2023-01-18'
excerpt: "ATFM delay codes, Transparency, Operations, Capacity"
bibliography: [../../../static/bib/aviation.bib]
link-citations: true
dwnld_i: <i class="fa pru fa-download"></i>
tags: Performance, Transparency, Operations, Capacity
---
```{r echo = FALSE, message = FALSE, warning = FALSE}
# run setup script
source(here::here("_common.R"))
```
 
<br>
<div class="container">
<div class="row align-items-start">

For several years, the PRC has highlighted that the existing ATFCM process could be improved to provide greater transparency to stakeholders, in particular in the way in which ATFM delays are attributed.

The current ATFCM process gives guidelines that should be followed when the flow management position (FMP) of an ANSP is requesting ATFM regulations to be applied as a result of one, or more, capacity constraints. The guidelines are subject to interpretation and, as highlighted in previous PRC analysis, result in considerable inconsistencies in the reporting of ATFM delays. 

For a given situation, (despite the guidelines provided by NM) one ANSP may attribute ATFM delays to ATC Capacity, whereas a second ANSP facing an identical situation may attribute the delays to ATC staffing. Moreover, an ANSP may decide to classify ATFM delays either to ATC staffing or ATC capacity, depending on when exactly the absence of ATC staff was notified. In all of these cases, the airspace will have the exact same capacity shortfall, requiring the exact same ATFM regulations and ATFM delays. However, the airspace users will not have a clear picture as to the actual cause of the capacity constraint.

The PRC has previously proposed a strengthening of the ATFCM process, by developing strict procedures for attributing ATFM delay causes, instead of the current guidelines that lead to inconsistencies and opacity in monitoring capacity performance. 

The PRC tested two new additional codes aimed at improving transparency. The results of the trial with ANSPs are documented in the [technical note][tn_prc_dly_code].  

<a href="/library/prc_tn_ANSP_trials_add_dly_codes.pdf" data-toggle="tooltip" title="Download pdf version" target="_blank" class="btn btn-info" role="button"> Technical Note <br>  PRC trial with ANSPs to improve transparency in ATFCM operations <br> {{% dwnld_i %}} Download </a>

#### Notice
*The PRC has made every effort to ensure that the information and analysis contained in this document are as accurate and 
complete as possible. Despite these precautions, should you find any errors or inconsistencies we would be grateful if you 
could please bring them to the [Aviation Intelligence Unit's attention](mailto:PRU-Support@eurocontrol.int).*

The PRC would like to inform readers that this report has been produced without prejudice to the current regulatory system applied within the Single European Sky. 

</div>
</div>

[tn_prc_dly_code]: /library/prc_tn_ANSP_trials_add_dly_codes.pdf "Technical Note - PRC trial with ANSPs to improve transparency in ATFCM operations"