#------- LOCAL DEVELOPMENT/TESTING -------
# remember ending '/'
# baseurl = "/"
# see .Rprofile for publishDir, i.e. the place
# where generated HTML is put (the "public" dir in hugo parlance)
#-----------------------------------------


#--------------- PRODUCTION ---------------
# remember ending '/'
baseurl = "http://www.ansperformance.eu/"
# publishDir = "public/"
#-----------------------------------------



languageCode = "en-us"
title = "PRU Portal"
theme = "pru-theme"
googleAnalytics = "UA-62697169-2"
summaryLength = 10

customCSS = ["css/supplement.css"]


ignoreFiles = [
  "\\.Rmd$",
  "\\.Rmarkdown$",
  "_files$",
  "_cache$",
  "src$"
]

# Uncomment below to enable syntax highlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
# pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
    post = "/:year/:month/:day/:slug/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]

 [[menu.main]]
    name = "Home"
    identifier= "home"
    url = "/#/"
    weight = 5

  [[menu.main]]
    name = "PRC"
    pre = ""
    url = "/about/prc/"
    identifier = "prc"   
    weight = 10
  [[menu.main]]
    name = " COVID-19 crisis"
    pre = "<i class='fas fa-biohazard'></i>"
    url = "/covid/"
    identifier = "covid"
    parent = "prc"
    weight = 1
  [[menu.main]]
    name = "divider-prr2019"
    parent = "prc"
    weight = 2
  [[menu.main]]
    name = "Performance Review Report 2019 (Consultation)"
    post = " <i class='fas fa-xs fa-external-link-alt'></i>"
    url = "http://www.eurocontrol.int/publication/performance-review-report-prr-2019-consultation"
    identifier = "prr19"
    parent = "prc"
    weight = 3
  [[menu.main]]
    name = "Older Performance Review Reports"
    post = " <i class='fas fa-xs fa-external-link-alt'></i>"
    url = "https://www.eurocontrol.int/publication/performance-review-report-prr-2018"
    identifier = "prr"
    parent = "prc"
    weight = 4
  [[menu.main]]
    name = "ATM Cost-Effectiveness (ACE)"
    post = " <i class='fas fa-xs fa-external-link-alt'></i>"
    url = "https://www.eurocontrol.int/ACE/ACE-Home.html"
    identifier = "ace"
    parent = "prc"
    weight = 5
  [[menu.main]]
    name = "divider-abprc"
    parent = "prc"
    weight = 6    
  [[menu.main]]
    name = "About the Performance Review Commission (PRC)"
    url = "/about/prc/"
    identifier = "ab_prc"
    parent = "prc"
    weight = 7

  [[menu.main]]
    name = "Area"
    identifier = "dashboard"
    pre = ""
    url = "/dashboard/"
    weight = 15
  [[menu.main]]
    name = "Traffic"
    url = "/traffic/"
    identifier = "traffic"
    parent = "dashboard"
    weight = 1
  [[menu.main]]
    name = "Capacity"
    url = "/capacity/"
    identifier = "capacity"
    parent = "dashboard"
    weight = 2
  [[menu.main]]
    name = "Efficiency/ Environment"
    url = "/efficiency/"
    identifier = "efficiency"
    parent = "dashboard"
    weight = 3
  [[menu.main]]
    name = "Cost efficiency"
    url = "/cost_efficiency/"
    identifier = "cost-efficiency"
    parent = "dashboard"
    weight = 4

  [[menu.main]]
    name = "Views"
    pre = ""
    url = "/dashboard/stakeholder/"
    identifier = "stakeholder"   
    weight = 20
  [[menu.main]]
    name = "Air Navigation Service Provider"
    url = "/dashboard/stakeholder/ansp/"
    identifier = "Ansp"
    parent = "stakeholder"
    weight = 1
  [[menu.main]]
    name = "States"
    url = "/dashboard/stakeholder/state/"
    identifier = "State"
    parent = "stakeholder"
    weight = 2

  [[menu.main]]
    name = "Data"
    pre = ""
    url = "/data/"
    weight = 25

  [[menu.main]]
    name = "References"
    pre = ""
    url = "/reference/"
    identifier = "references"
    weight = 30
  [[menu.main]]
    name = "Methodology"
    url = "/methodology/"
    identifier = "methodology"
    parent = "references"
    weight = 1
  [[menu.main]]
    name = "Acronyms"
    url = "/acronym/"
    parent = "references"
    weight = 2
  [[menu.main]]
    name = "Definitions"
    url = "/definition/"
    parent = "references"
    weight = 3
  [[menu.main]]
    name = "Bibliography"
    url = "/bibliography/"
    parent = "references"
    weight = 4
  [[menu.main]]
    name = "divider2"
    parent = "references"
    weight = 5
  [[menu.main]]
    name = "ICAO GANP"
    post = " <i class='fas fa-xs fa-external-link-alt'></i>"
    url = "https://www4.icao.int/ganpportal/"
    parent = "references"
    weight = 6

 [[menu.main]]
    name = "About"
    identifier= "about"
    url = "/about/us/"
    weight = 35
  [[menu.main]]
    name = "About us"
    url = "/about/us/"
    identifier = "pru"
    parent = "about"
    weight = 1
  [[menu.main]]
    name = "Release notes"
    url = "/post/"
    identifier = "release"
    parent = "about"
    weight = 2
  [[menu.main]]
    name = "Disclaimer"
    url = "/about/disclaimer/"
    identifier = "disclaimer"
    parent = "about"
    weight = 3

  [[menu.main]]
    name = "SES"
    identifier= "ses"
    url = " "
    weight = 40
  [[menu.main]]
    name = "Single European Sky (SES) Portal"
    post = " <i class='fas fa-xs fa-external-link-alt'></i>"
    url = "https://www.eurocontrol.int/prudata/dashboard/vis/2019/"
    identifier = "ses-link"
    parent = "ses"
    weight = 1



[[menu.sidenav]]
    name = "Overview"
    url = "/prcq/"
    identifier= "overview"
    weight = 10
[[menu.sidenav]]
    name = "Traffic"
    url = "/prcq/traffic/"
    identifier= "traffic"
    weight = 20
[[menu.sidenav]]
    name = "Ops En-route"
    url = "/prcq/ops-en-route/"
    identifier= "ops-en-route"
    weight = 40
[[menu.sidenav]]
    name = "Ops Airport"
    url = "/prcq/ops-airport/"
    identifier= "ops-airport"
    weight = 50

[[menu.covid]]
    name = "Overview"
    url = "/covid/"
    identifier= "overview"
    weight = 10
 [[menu.covid]]
    name = "Traffic (ANSP)"
    url = "/covid/ansp_flts"
    identifier= "ansp_flts"
    weight = 20
[[menu.covid]]
    name = "Grounded aircraft"
    url = "/covid/acft_ground"
    identifier= "parking"
    weight = 30
[[menu.covid]]
    name = "En route revenue"
    url = "/cost_efficiency/ert_crg"
    identifier= "ref_charges"
    weight = 40

[[menu.traffic]]
    name = "Overview"
    url = "/traffic"
    identifier= "overview"
    weight = 10
 [[menu.traffic]]
    name = "State"
    url = "/traffic/state"
    identifier= "state"
    weight = 20
[[menu.traffic]]
    name = "Area Control center"
    url = "/traffic/acc"
    identifier= "acc"
    weight = 30
[[menu.traffic]]
    name = "Airport"
    url = "/traffic/airport"
    identifier= "airport"
    weight = 40
[[menu.traffic]]
    name = "Aircraft Operators"
    url = "/traffic/ao"
    identifier= "ao"
    weight = 50
[[menu.traffic]]
    name = "Traffic forecast"
    url = "/traffic/statfor"
    identifier= "statfor"
    weight = 60

[[menu.capacity]]
    name = "Overview"
    url = "/capacity"
    identifier= "overview"
    weight = 10
 [[menu.capacity]]
    name = "En-route ATFM delays"
    url = "/capacity/atfm_ert"
    identifier= "atfm_ert"
    weight = 20
[[menu.capacity]]
    name = "Airport ATFM delays"
    url = "/capacity/atfm_apt"
    identifier= "atfm_apt"
    weight = 30


[[menu.efficiency]]
    name = "Overview"
    url = "/efficiency"
    identifier= "overview"
    weight = 10
 [[menu.efficiency]]
    name = "Horizontal flight efficiency"
    url = "/efficiency/hfe"
    identifier= "hfe"
    weight = 20
[[menu.efficiency]]
    name = "Vertical flight efficiency"
    url = "/efficiency/vfe"
    identifier= "vfe"
    weight = 30
[[menu.efficiency]]
    name = "Terminal area"
    url = "/efficiency/asma"
    identifier= "asma"
    weight = 40
[[menu.efficiency]]
    name = "Taxi out"
    url = "/efficiency/taxiout"
    identifier= "taxiout"
    weight = 50

[[menu.cost_efficiency]]
    name = "Overview"
    url = "/cost_efficiency"
    identifier= "overview"
    weight = 10
 [[menu.cost_efficiency]]
    name = "ATM Cost Efficiency Benchmark (ACE)"
    url = "/cost_efficiency/ace"
    identifier= "ace"
    weight = 20
[[menu.cost_efficiency]]
    name = "Unit rate and costs"
    url = "/cost_efficiency/unitrate"
    identifier= "unit"
    weight = 30
[[menu.cost_efficiency]]
    name = "En-route revenue"
    url = "/cost_efficiency/ert_crg"
    identifier= "ref_charges"
    weight = 40


[params]
  includeBootstrapJs = false
  showActiveNav = true
  containerMaxWidth = "960px"
  dateFormat = "Jan 2, 2006"
  hideFooter = false
  sitetosearch = "ansperformance.eu"

  [params.logo]
    url = "images/euctrl-logo-noname.png"
    height = 30
    alt = "PRU"

  [params.owner]
    name = "European Organisation for the Safety of Air Navigation (EUROCONTROL)"
    shortname = "EUROCONTROL"
    location = "Brussels, Belgium"
    twitter = "eurocontrol"
    github =  "euctrl-pru"
    email = "PRU-Support@eurocontrol.int"


# see https://matjaz.it/hugo-power-user-make-it-web-friendly-1/
enableRobotsTXT = true

# see https://matjaz.it/hugo-power-user-make-it-web-friendly-1/
# TODO: set Google Webmaster tools
[sitemap]
  changefreq = "weekly"
  priority = 0.5
