[build] 
publish = "public"
command = "git submodule update --init --recursive --depth=1 && hugo -d public --gc --minify -b $DEPLOY_URL"

[context.production.environment]
  HUGO_VERSION = "0.65.3" # if older, use format: 0.53 (no trailing zero)
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
  [context.deploy-preview.environment]
  HUGO_VERSION = "0.65.3"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
  [context.branch-deploy.environment]
    HUGO_VERSION = "0.65.3" # if older, use format: 0.53 (no trailing zero)


# A basic redirect rule
[[redirects]]
  from = "/references/*"
  to = "/:splat"

[[redirects]]
  from = "/graphs/*"
  to = "/dashboard/performance-area/:splat"

[[redirects]]
  from = "/nvctr/*"
  to = "https://nvctr.ansperformance.eu/:splat"
  status = 301
  
[[redirects]]
  from = "/definition/eurocontrol_area.html"
  to = "/definition/eurocontrol-area/"
  status = 301

[[redirects]]
  from = "/definition/atfm_delay_codes.html"
  to = "/definition/atfm-delay-codes/"
  status = 301

[[redirects]]
  from = "/definition/atfm_delay.html"
  to = "/definition/atfm-delay/"
  status = 301

[[redirects]]
  from = "/definition/additional_asma_time.html"
  to = "/definition/additional-asma-time/"
  status = 301

[[redirects]]
  from = "/definition/atfm_slot_adherence.html"
  to = "/definition/atfm-slot-adherence/"
  status = 301

[[redirects]]
  from = "/definition/additional_taxi-out_time.html"
  to = "/definition/additional-taxi-out-time/"
  status = 301

[[redirects]]
  from = "/definition/atc_pre-departure_delay.html"
  to = "/definition/atc-pre-departure-delay/"
  status = 301


[[redirects]]
  from = "/definition/composite_flight_hour.html"
  to = "/definition/composite-flight-hour/"
  status = 301

