---
title: IATA delay codes
slug: iata-delay-codes
bibliography: [../../../static/bib/aviation.bib]
link-citations: true
biblio-style: apalike
---
```{r echo = FALSE, message = FALSE, warning = FALSE}
# run setup script
source(here::here("_common.R"))
```

The table below summarises the IATA Delay Codes from [@iata:delaycodes].
For a little introduction to these codes see [@wiki:iatadelaycodes].


```{r}
library(readr)
library(dplyr)
library(here)
library(gt)

read_csv("ahm730.csv") %>% 
  mutate(id = if_else(is.na(id),"-", id)) %>% 
  gt(groupname_col = "group") %>% 
  # cols_merge(
  #   columns = c(code, id),
  #   pattern = "{1} ({2})"
  #   ) %>% 
  tab_header(
    title = "Standard IATA Delay Codes",
    subtitle = "Doc AHM730"
  )
```


## See Also

* IATA Delay codes table ([PDF](/library/iata-delay-codes.pdf))
* Appendix of [All-causes delay and cancellations to Air Transport Europe Quaterly Reports](https://www.eurocontrol.int/library?keywords=All-causes+delay+and+cancellations+to+Air+Transport+Europe&sort_by=search_api_relevance&f%5B0%5D=activity%3A777&f%5B1%5D=product%3A805)


## References

