---
title: COVID-19 outbreak
date: '2020-03-13'
---
<style type="text/css">
.img-responsive {
    margin: 0 auto;
    max-width: 75%
}

.resp-container {
    position: relative;
    overflow: hidden;
    padding-top: 50.0%;
}

.resp-iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 110%;
    border: 0;
}
</style>

With a pandemic sweeping its way across the globe, the entire aviation industry is facing an unprecedented challenge.  
Nobody can currently answer the most pressing question, namely how long will the crisis last, how bad it will be, and how to get back to normality?

Complementary to the [EUROCONTROL web page][ectlweb] which provides daily situation updates in an [interactive dashboard][ectl_daily], the goal of this site is to provide relevant high level snapshots of the crisis particularly related to performance topics as more data becomes available. 

The analyisis below shows the evolution of the daily flights in the [EUROCONTROL Member States][ectlmemb] between 01 January and 24 March for the years 2010, 2019 and 2020. The year 2010 was included as a reference because of the volcanic ash crisis from 14-20 April which brought European aviation close to a standstill.
The analysis shows the dramatic reduction in traffic starting at the beginning of March. Although many airlines already suspended operations the bottom has not yet been and traffic is still reducing further.   

<div class="resp-container">
<iframe class="resp-iframe" src="https://datastudio.google.com/embed/reporting/a960e72f-e79d-47f4-8ef1-e7c5cecb1ac5/page/jwMJB" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
The table below provides a similar overview at Air Navigation Service Provider level for the period between 01 January 24 March. As usual, the corresponding data will be available for download in the [data section](/data/) as soon as we have completed and processed the full month.    

<div class="resp-container">
<iframe class="resp-iframe" src="https://datastudio.google.com/embed/reporting/a960e72f-e79d-47f4-8ef1-e7c5cecb1ac5/page/JSNJB" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>

<!-- change the following as you best see fit (I did not want to hardoce in the covid list template) -->

[ectl_daily]: https://www.eurocontrol.int/Economics/DailyTrafficVariation-States.html "Daily traffic updates"
[ectlweb]: https://www.eurocontrol.int/ "EUROCONTROL web page"
[ectlmemb]: https://www.eurocontrol.int/about-us#member-states "EUROCONTROL Member States"