---
title: COVID-19 - Impact on traffic
date: '2020-04-16'
---

<style type="text/css">
.img-responsive {
    margin: 0 auto;
    max-width: 75%
}

.resp-container {
    position: relative;
    overflow: hidden;
    padding-top: 70.0%;
}

.resp-iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 110%;
    border: 0;
}
</style>

<div class="container">
<div class="row align-items-start">
<div class="col-sm-6">>
The analysis shows the evolution of the flights (moving 7 day average) in the [EUROCONTROL Area](/definition/eurocontrol-area/) for the years 2010, 2019 and 2020. 

Although the dimension of the COVID-19 crisis is of a completely different order of magnitude, the year 2010 was included as a reference because of the volcanic ash crisis from 14-20 April which brought European aviation close to a standstill.

The analysis suggests that the turning point was reached in mid April 2020. Since then traffic very slowly started to grow again. <br>

<a href="https://www.eurocontrol.int/Economics/DailyTrafficVariation-States.html" class="btn btn-danger" role="button"><i class='fas fa-xs fa-exclamation-triangle'></i> For daily traffic statistics by State, Area Control Center (ACC), Airport, and Aircraft Operator level please visit our interactive dashboard!</a>
</div>

<div class="col-sm-6">
<div class="resp-container">
<iframe class="resp-iframe" src="https://datastudio.google.com/embed/reporting/b2b43aeb-ce1d-4c7e-961a-8bb646368111/page/jwMJB" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
</div>
</div>
</div>

### COVID-19 impact by ANSP
The table below provides an overview of the traffic evolution at Air Navigation Service Provider level (all controlled flights including overflights).

The corresponding data is available for download in the [data section](/data/).<br>
<div class="resp-container">
<iframe class="resp-iframe" src="https://datastudio.google.com/embed/reporting/a960e72f-e79d-47f4-8ef1-e7c5cecb1ac5/page/JSNJB" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>