---
title: Evolution of APDF Transition to IR390
---

```{r echo = FALSE, message = FALSE, warning = FALSE}
# run setup script
source(here::here("_common.R"))

library(readr)
library(here)
library(dplyr)
library(ggplot2)
library(ggrepel)

```


```{r apdf-data, echo=FALSE}
cols <- cols(
  AIRPORT = col_character(),
  APT_COUNTRY = col_character(),
  APT_NAME = col_character(),
  DATE_FROM = col_date(format = "%Y%m"),
  FORMAT = col_character()
)
apdf <- read_csv(here("data-config", "apdf-transition-IR691.csv"), col_types = cols)
```

# Transition to IR390

```{r plot-evolution}
apdf_evo <- apdf %>% 
  group_by(DATE_FROM, FORMAT) %>% 
  count()


ggplot(apdf_evo) +
  geom_point(aes(x = DATE_FROM, y = n, group = FORMAT, colour = FORMAT)) +
  geom_step(aes(DATE_FROM, n, group = FORMAT, colour = FORMAT)) +
  geom_text_repel(
    data = subset(apdf_evo, DATE_FROM == max(DATE_FROM)),
    aes(x = DATE_FROM, y = n, label = n, color = FORMAT),
    size = 5,
    hjust = -3,
    segment.color = NA,
    show.legend = FALSE
  ) +
  geom_text_repel(
    data = subset(apdf_evo, DATE_FROM == min(DATE_FROM)),
    aes(x = DATE_FROM, y = n, label = n, color = FORMAT),
    size = 5,
    segment.color = NA,
    show.legend = FALSE
  ) +
  labs(title = "APDF data format submission",
       subtitle = "Evolution of format adoption",
       x = "year",
       y = "number of airports",
       colour = "APDF format") +
  theme(legend.position = "bottom")
  
```

