---
title: "Brazil"
---

Brazil and Europe represented by DECEA and EUROCONTROL engaged in 2016 in a cooperation agreement. Amongst other activities, this agreement entails the collaboration in developing in initial operational performance benchmarking exercise for Air Navigation Services (ANS).
Based on this agreement, DECEA started a Working Group, which has become the ATM Performance Indicators Management Committee, aiming at improving performance-based management. Through lessons learnt from the best practices observed at EUROCONTROL, and in particular PRU, DECEA established the Performance Section.

DECEA Performance Section and the PRU have established a joint project to foster the common understanding and harmonised interpretation of the proposed ICAO GANP indicators. The technical work has been conducted throughout the recent years comprising joint workshops and a series of web-based discussion sessions and face-to-face meetings. 
It also comprised the identification and validation of comparable data sources and joint data processing and analysis to produce this report.

<strong><p class="text-danger">The initial comparison report is in its finalisation stage and planned to be published in May/June 2021.</p></strong>
