---
title: Traffic Overview
dwnld_i: <i class="fa pru fa-download"></i>
---

```{r, echo=FALSE, include=FALSE}
# All defaults
## libraries
library(fs)
library(tibble)
library(dplyr)
library(stringr)
library(googlesheets4)
library(lubridate)
library(plotly)
```
<script>
  function resizeIframe(obj) {
    obj.style.height = obj.contentWindow.document.documentElement.scrollHeight + 'px';
  }
</script>

<style type="text/css">
  .img-responsive {
      margin: 0 auto;
      max-width: 75%
  }
  

  .resp-iframe {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      border: 0;
   }  
  
  .col-12 {
    margin: 0px;
    padding: 0px
  }
  
  .Scorecard_subt {
    text-align: left;
  }

@media screen and (min-width:1000px) {
  .flex-container {
    display: flex;
  }

  #traffic-plot{
  margin-left:40px
  }
  
  .Mycolumn {
    width: 50%;
    text-align: justify;
<!-- margin-right: 5px -->
  <!-- margin-left: 0px; -->
  <!-- background-color: #7f7f7f; -->
  }

  .Mycolumn2 {
    width: 50%;
    text-align: justify;
    <!-- margin-left: 0px; -->
    <!-- margin-right: 5px -->
  }

  .resp-container {
      position: relative;
      overflow: hidden;
      padding-top: 55.0%;
  }

 #aos, #ansps {
    margin-right: 10px
 }
  .Scorecard {
    margin: 0px;
    padding: 0px;
    font-size: 32px;
    font-weight: bold;
    color: #161b21;
    text-align: left;
  }

  .Scorecard2 {
    margin: 0px;
    padding: 0px;
    padding-top: 7px;
    font-size: 26px;
    font-weight: bold;
    color: #161b21;
    text-align: left;
  }
  
}

@media screen and (max-width:1000px) {
  .Mycolumn {
    width: 100%;
    margin-right: 0px;
    text-align: justify;
  }
  
  .Mycolumn2 {
    width: 100%;
    margin-left: 0px;
    margin-right: 0px;
    text-align: justify;
  }
  
  .Scorecard {
    margin: 0px;
    padding: 0px;
    font-size: 20px;
    font-weight: bold;
    color: #161b21;
    text-align: left;
  }

  .resp-container {
      position: relative;
      overflow: hidden;
      padding-top: 85.0%;
  }

  .Scorecard2 {
    margin: 0px;
    padding: 0px;
    padding-top: 7px;
    font-size: 18px;
    font-weight: bold;
    color: #161b21;
    text-align: left;
  }
}

  </style>


This page provides an overview of the traffic situation in the [EUROCONTROL Area](/definition/eurocontrol-area/). For a more detailed analysis consult our <a href="https://www.eurocontrol.int/Economics/DailyTrafficVariation-States.html " target="_blank">Daily traffic variation dashboard</a>. Information on en-route and terminal [service units](/acronym/su/) from the <a href="https://www.eurocontrol.int/crco" target="_blank">Central Route Charges Office of EUROCONTROL (CRCO)</a> is available from our <a href="https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteMainDashboard.html" target="_blank">Service Units dashboard</a>.

<!-- Network Traffic section -->
<div class="container" style="margin: 0px; padding: 0px">

#### EUROCONTROL area (Network view)
<!-- Daily traffic graphs and scorecards -->
<div class="flex-container" style=" margin-bottom: 5px;">
<div class="Mycolumn" >
<div class="row" style="margin:0px; margin-bottom: 5px;background-color: #f2f2f2; border-radius: 5px; width: 101%;">
<div class="col-12" ; style="margin-left: 16px;  ">
  <p id="last_day" style="font-weight: bold; margin-bottom: 0px; color: #0070c0;">Day</p>
</div>
<div class="col-3" ; style="margin: 0px; ">
  <p id="day_traffic" class="Scorecard"></p>
  <p class="Scorecard_subt">flights</p>
</div>
<div class="col-3" ; style="margin: 0px;  ">
  <p id="dif_day_prev_week" class="Scorecard2" ></p>
  <p class="Scorecard_subt">vs prev. week</p>
</div>
<div class="col-3" ; style="margin: 0px; ">
  <p id="dif_day_2019" class="Scorecard2"></p>
  <p class="Scorecard_subt">vs 2019</p>
</div>
<div class="col-3" ; style="margin: 0px;  ">
  <p id="dif_day_prev_year" class="Scorecard2"></p>
  <p class="Scorecard_subt">vs 2021</p>
</div>
</div><!-- closes row -->
<div class="row" style="margin:0px; margin-bottom: 5px;background-color: #f2f2f2; border-radius: 5px; width: 101%;">
<div class="col-12" ; style="margin-left: 16px; ">
  <p id="last_week" style="font-weight: bold; margin-bottom: 0px; color: #0070c0;">Week</p>
</div>
<div class="col-3" ; style="margin: 0px;  ">
  <p id="week_traffic" class="Scorecard"></p>
  <p id="avg_week_traffic" class="Scorecard_subt"></p>
</div>
<div class="col-3" ; style="margin: 0px;  ">
  <p id="dif_week_prev_week" class="Scorecard2" ></p>
  <p class="Scorecard_subt">vs prev. week</p>
</div>
<div class="col-3" ; style="margin: 0px; ">
  <p id="dif_week_2019" class="Scorecard2"></p>
  <p class="Scorecard_subt">vs 2019</p>
</div>
<div class="col-3" ; style="margin: 0px;  ">
  <p id="dif_week_prev_year" class="Scorecard2"></p>
  <p class="Scorecard_subt">vs 2021</p>
</div>
</div><!-- closes row -->
<div class="row" style="margin:0px; margin-bottom: 5px;background-color: #f2f2f2; border-radius: 5px; width: 101%;">
<div class="col-12" ; style="margin-left: 16px;">
  <p id="y2d_day_text" style="font-weight: bold; margin-bottom: 0px; color: #0070c0;">Year to date</p>
</div>
<div class="col-3" ; style="margin: 0px;  ">
  <p id="y2d_traffic" class="Scorecard"></p>
  <p id="avg_y2d_traffic" class="Scorecard_subt"></p>
</div>
<div class="col-3" ; style="margin: 0px;  ">
</div>
<div class="col-3" ; style="margin: 0px; ">
  <p id="dif_y2d_2019" class="Scorecard2"></p>
  <p class="Scorecard_subt">vs 2019</p>
</div>
<div class="col-3" ; style="margin: 0px;  ">
  <p id="dif_y2d_prev_year" class="Scorecard2"></p>
  <p class="Scorecard_subt">vs 2021</p>
</div>
</div><!-- closes row -->
</div><!-- closes Mycolumn -->
<div class="Mycolumn2">
<div class="col-12" >

<div style=" margin-top: 0px; height: 400px;">
<iframe id="traffic-plot" class="resp-iframe" src="https://www.eurocontrol.int/Economics/Oscar/plot-traffic-lp.html" frameborder="0" style="border:0; margin-top: 10px;" >
</iframe>
<!-- <iframe class="resp-iframe" src="https://datastudio.google.com/embed/reporting/4efb3da2-6cd8-4778-ab2b-0fd0cbe71db2/page/tvomC" frameborder="0" style="border:0" allowfullscreen></iframe> -->
</div>

</div><!-- closes col-12 -->
</div><!-- closes Mycolumn2 -->
</div><!-- closes flex-container -->
<a href="https://www.eurocontrol.int/Economics/Download/Network_Traffic.xlsx" class="btn btn-info" role="button" target="_blank">{{% dwnld_i %}} Download network data</a>

<!-- Stakeholders section -->
<div class="container" style="margin: 0px; padding: 0px">

#### Stakeholder views
Only the top 40 in terms of flights are shown in the tables (latest day, rolling week and year to date).
<br>

<div class="flex-container" style=" margin-bottom: 5px;">

<div class="Mycolumn" >
<div class="col-12" style=" margin: 0px; " >
<h5>Aircraft Operators</h5>
<div id="aos" class="resp-container">
<iframe class="resp-iframe" src="https://www.eurocontrol.int/Economics/Oscar/plot-ao-ranking-table.html" frameborder="0" style="border:0, padding-left: 0px" allowfullscreen></iframe>
<!-- <iframe class="resp-iframe" src="https://datastudio.google.com/embed/reporting/7cb12f8c-175b-4a00-8e41-4995bc78464c/page/p_01akhlhpsc" frameborder="0" style="border:0" allowfullscreen loading="lazy"></iframe> -->
</div>
</div>
<br>
<a href="https://www.eurocontrol.int/directory/airline-groups-lookup" target="_blank" >See aircraft operator groupings</a>
</div>
<div class="Mycolumn2">
<div class="col-12" style=" margin: 0px; " >
<h5>Airports</h5>
<div id="apts" class="resp-container">
<iframe class="resp-iframe" src="https://www.eurocontrol.int/Economics/Oscar/plot-apt-ranking-table.html" frameborder="0" style="border:0" allowfullscreen></iframe><!-- <iframe class="resp-iframe" src="https://datastudio.google.com/embed/reporting/71726332-25f1-412b-a902-50182fbc00c7/page/obGnC" frameborder="0" style="border:0" allowfullscreen loading="lazy"></iframe> -->
</div></div>
</div>
</div>

<div class="flex-container" style=" margin-bottom: 5px;">
<div class="Mycolumn" >
<div class="col-12" style=" margin: 0px; " >
<h5>Air Navigation Service Providers (ANSPs)</h5>
<div id="ansps" class="resp-container" style="align-text: center">Comming soon!
<!-- <iframe class="resp-iframe" src="https://datastudio.google.com/embed/reporting/82e3ef8b-e5c9-4ff1-a983-05bce140e029/page/9v7pC" frameborder="0" style="border:0" allowfullscreen loading="lazy"></iframe> -->
</div>
</div>
</div>
<div class="Mycolumn2">
<div class="col-12" style=" margin: 0px; " >
<h5>Country Pairs</h5>
<div id="cps" class="resp-container">
<iframe class="resp-iframe" src="https://www.eurocontrol.int/Economics/Oscar/plot-ctrypair-ranking-table.html" frameborder="0" style="border:0;" allowfullscreen></iframe><!-- <iframe class="resp-iframe" src="https://datastudio.google.com/embed/reporting/74850727-d77f-4508-b312-114d40a3a7e6/page/tAPnC" frameborder="0" style="border:0" allowfullscreen loading="lazy"></iframe> -->
</div>
</div>
</div></div>
</div>
<a href="https://www.eurocontrol.int/Economics/Download/Stakeholder_Traffic.xlsx" class="btn btn-info" role="button" target="_blank">{{% dwnld_i %}} Download stakeholder data</a>


<!-- script for traffic figures -->
<script type="text/javascript">
  var data
  
  window.onload = function() {
   window.addEventListener('message', function (e) {
   var $iframe = $('#traffic-plot');

   data = JSON.parse(e.data);

   UpdateTraffic();
   
  }, false);
    
}
 
 function UpdateTraffic() { 
     // Calculate datestrings
   var last_day = new Date(data.LAST_DATA_DAY);
   var last_day_text = last_day.toString();
       last_day_text = last_day_text.substring(8, 11) + last_day_text.substring(4, 8) + last_day_text.substring(11, 15);
 
 
 //calculate 1st day of rolling week and string
  var first_week_day = new Date();
      first_week_day = first_week_day.setDate(last_day.getDate()-6);
      first_week_day = new Date(first_week_day);
      first_week_day = first_week_day.toString();
  var last_week_text = first_week_day.substring(8, 11) + (last_day_text.substring(3, 7) == first_week_day.substring(4, 8) ? "" :  first_week_day.substring(4, 8)) + "- " + last_day_text;

  var y2d_day_text = last_day_text.substring(3, 7) == "Jan " ? "01 - " + last_day_text : "01 Jan - " + last_day_text;
 
 // Calculate traffic scorecard values
  var day_traffic = data.DAY_TFC;
  
  var dif_day_prev_week = Math.round(data.DAY_TFC_PREV_WEEK_PERC*100);
      dif_day_prev_week = (dif_day_prev_week >= 0) ? "+" + dif_day_prev_week : "" + dif_day_prev_week ;
  
  var dif_day_2019 = Math.round(data.DAY_TFC_DIFF_2019_PERC*100);
      dif_day_2019 = (dif_day_2019 >= 0) ? "+" + dif_day_2019 : "" + dif_day_2019;
  
  var dif_day_prev_year = Math.round(data.DAY_DIFF_PREV_YEAR_PERC*100);
      dif_day_prev_year = (dif_day_prev_year >= 0) ? "+" + dif_day_prev_year : "" + dif_day_prev_year ;

  var week_traffic = data.TOTAL_ROLLING_WEEK;
  var avg_week_traffic = Math.round(week_traffic/7);
  
  var dif_week_prev_week = Math.round(data.DIF_PREV_WEEK_PERC*100);
      dif_week_prev_week = (dif_week_prev_week >= 0) ? "+" + dif_week_prev_week : "" + dif_week_prev_week;
  
  var dif_week_2019 = Math.round(data.DIF_ROLLING_WEEK_2019_PERC*100);
      dif_week_2019 = (dif_week_2019 >= 0) ? "+" + dif_week_2019 : "" + dif_week_2019;
  
  var dif_week_prev_year = Math.round(data.DIF_WEEK_PREV_YEAR_PERC*100);
      dif_week_prev_year = (dif_week_prev_year >= 0) ? "+" + dif_week_prev_year : "" + dif_week_prev_year;
   
  var y2d_traffic = data.Y2D_TFC_YEAR;
  var avg_y2d_traffic = Math.round(data.Y2D_AVG_TFC_YEAR);
  var dif_y2d_2019 = Math.round(data.Y2D_DIFF_2019_PERC*100);
      dif_y2d_2019 = (dif_y2d_2019 >= 0) ? "+" + dif_y2d_2019 : "" + dif_y2d_2019;
  var dif_y2d_prev_year = Math.round(data.Y2D_DIFF_PREV_YEAR_PERC*100);
      dif_y2d_prev_year = (dif_y2d_prev_year >= 0) ? "+" + dif_y2d_prev_year : "" + dif_y2d_prev_year;


// Update scorecard values
  document.getElementById("last_day").innerHTML = "Day (" + last_day_text + ")";
  document.getElementById("last_week").innerHTML = "Rolling week (" + last_week_text + ")";
  document.getElementById("y2d_day_text").innerHTML = "Year to date (" + y2d_day_text + ")";
   
  document.getElementById("day_traffic").innerHTML = String(day_traffic).replace(/(.)(?=(\d{3})+$)/g, '$1,');
  document.getElementById("dif_day_prev_week").innerHTML = dif_day_prev_week + '%';
  document.getElementById("dif_day_2019").innerHTML = dif_day_2019 + '%';
  document.getElementById("dif_day_prev_year").innerHTML = dif_day_prev_year + '%';
  
  document.getElementById("week_traffic").innerHTML = String(week_traffic).replace(/(.)(?=(\d{3})+$)/g, '$1,');
  document.getElementById("avg_week_traffic").innerHTML = String(avg_week_traffic).replace(/(.)(?=(\d{3})+$)/g, '$1,') + " daily flights";
  document.getElementById("dif_week_prev_week").innerHTML = dif_week_prev_week + '%';
  document.getElementById("dif_week_2019").innerHTML = dif_week_2019 + '%';
  document.getElementById("dif_week_prev_year").innerHTML = dif_week_prev_year + '%';
  
  document.getElementById("y2d_traffic").innerHTML = String(y2d_traffic).replace(/(.)(?=(\d{3})+$)/g, '$1,');
  document.getElementById("avg_y2d_traffic").innerHTML = String(avg_y2d_traffic).replace(/(.)(?=(\d{3})+$)/g, '$1,') + " daily flights";
  document.getElementById("dif_y2d_2019").innerHTML = dif_y2d_2019 + '%';
  document.getElementById("dif_y2d_prev_year").innerHTML = dif_y2d_prev_year + '%';


 }  
  
</script>

