---
layout: default
title: "Traffic Overview"
---

```{r, echo=FALSE, include=FALSE}
## libraries
library(fs)
library(tibble)
library(dplyr)
library(stringr)
library(googlesheets4)
library(lubridate)
```


<style type="text/css">

  .resp-iframe {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      border: 0;
   }  
   
@media screen and (min-width:960px) {
  .Scorecard {
    margin: 0px;
    padding: 0px;
    font-size: 32px;
    font-weight: bold;
    color: #161b21;
    text-align: left;
  }

  .Scorecard2 {
    margin: 0px;
    padding: 0px;
    padding-top: 7px;
    font-size: 26px;
    font-weight: bold;
    color: #161b21;
    text-align: left;
  }
  
  #delay-plot{
    margin-left:10px;
  }
  
}

@media screen and (max-width:960px) {

  .Scorecard {
    margin: 0px;
    padding: 0px;
    font-size: 20px;
    font-weight: bold;
    color: #161b21;
    text-align: left;
  }

  .Scorecard2 {
    margin: 0px;
    padding: 0px;
    padding-top: 7px;
    font-size: 18px;
    font-weight: bold;
    color: #161b21;
    text-align: left;
  }
}


@media screen and (max-width:1200px) {

  #acc-delay, #apt-delay {
    height: 350px;
  }
}

@media screen and (min-width:1200px) {

  #acc-delay, #apt-delay {
    height: 680px;
  }
}


  </style>
  
This page provides an overview of the traffic, [ATFM delay](/definition/atfm-delay/), [punctuality (OTP15)](/definition/punctuality/) and percentage of [operated schedules](/definition/opschedules/) in the [EUROCONTROL Area](/definition/eurocontrol-area/). For a more detailed analysis consult our [Daily traffic variation dashboard](https://www.eurocontrol.int/Economics/DailyTrafficVariation-States.html){target="_blank"}. Information on en-route and terminal [service units](/acronym/su/) from the [Central Route Charges Office of EUROCONTROL (CRCO)](https://www.eurocontrol.int/crco){target="_blank"} is available from our [Service Units dashboard](https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteMainDashboard.html){target="_blank"}. 

<ul class="nav nav-tabs mb-1">
  <li class="nav-item">
    <a class="nav-link" href="/traffic/">Flights</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" aria-current="page">ATFM Delays</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/traffic/punctuality">Punctuality</a>
  </li> 
</ul>

<!-- Network dly section -->
#### EUROCONTROL area (Network view)  
<div class="container">
<div class="row align-items-start">
<div class="col-md-6">

<div class="row align-items-start mb-1" style="background-color: #f2f2f2; border-radius: 5px;">
<div class="col-12" >
  <p id="last_day" style="font-weight: bold; margin-bottom: 0px; color: #0070c0;">Day</p>
</div>
<div class="col-3">
  <p id="day_dly" class="Scorecard"></p>
  <p class="Scorecard_subt">minutes</p>
</div>
<div class="col-3">
  <p id="dif_day_prev_week" class="Scorecard2" ></p>
  <p class="Scorecard_subt">vs prev. week</p>
</div>
<div class="col-3" >
  <p id="dif_day_2019" class="Scorecard2"></p>
  <p class="Scorecard_subt">vs 2019</p>
</div>
<div class="col-3">
  <p id="dif_day_prev_year" class="Scorecard2"></p>
  <p class="Scorecard_subt">vs 2021</p>
</div>
</div><!-- closes row -->

<!-- week -->
<div class="row align-items-start mb-1" style="background-color: #f2f2f2; border-radius: 5px;">
<div class="col-12" >
  <p id="last_week" style="font-weight: bold; margin-bottom: 0px; color: #0070c0;"></p>
</div>
<div class="col-3">
  <p id="week_dly" class="Scorecard"></p>
  <p id="avg_week_dly" class="Scorecard_subt"></p>
</div>
<div class="col-3">
  <p id="dif_week_prev_week" class="Scorecard2" ></p>
  <p class="Scorecard_subt">vs prev. week</p>
</div>
<div class="col-3" >
  <p id="dif_week_2019" class="Scorecard2"></p>
  <p class="Scorecard_subt">vs 2019</p>
</div>
<div class="col-3">
  <p id="dif_week_prev_year" class="Scorecard2"></p>
  <p class="Scorecard_subt">vs 2021</p>
</div>
</div><!-- closes row -->

<!-- y2d -->
<div class="row align-items-start mb-1" style="background-color: #f2f2f2; border-radius: 5px;">
<div class="col-12" >
  <p id="y2d_day_text" style="font-weight: bold; margin-bottom: 0px; color: #0070c0;"></p>
</div>
<div class="col-3">
  <p id="y2d_dly" class="Scorecard"></p>
  <p id="avg_y2d_dly" class="Scorecard_subt"></p>
</div>
<div class="col-3">
</div>
<div class="col-3" >
  <p id="dif_y2d_2019" class="Scorecard2"></p>
  <p class="Scorecard_subt">vs 2019</p>
</div>
<div class="col-3">
  <p id="dif_y2d_prev_year" class="Scorecard2"></p>
  <p class="Scorecard_subt">vs 2021</p>
</div>
</div><!-- closes row -->

</div><!-- closes col md-6-->

<div class="col-md-6">
<div style=" margin-top: 0px; height: 420px;">
<iframe id="delay-plot" class="resp-iframe" src="https://www.eurocontrol.int/Economics/Oscar/plot-delay-traffic-lp.html" frameborder="0" style="border:0;" >
</iframe>
</div><!-- closes iframe container -->
</div><!-- closes col -->
</div><!-- closes row -->
</div><!-- closes container -->
<a href="https://www.eurocontrol.int/Economics/Download/Network_Delay.xlsx" class="btn btn-info" role="button" target="_blank">{{% dwnld_i %}} Download network delay data</a>

<div class="flex-container mt-2">

<div class="row align-items-start">
<div class="col-md-6" >
#### ACC view
Total [ATFM delay](/definition/atfm-delay/) per ACC.
<div class="row align-items-start">
<div class="col-12">
<div id="acc-delay">
<iframe id="acc-delay-table" class="resp-iframe" src="https://www.eurocontrol.int/Economics/Oscar/plot-acc-delay-ranking-table.html" frameborder="0" style="border:0;" >
</iframe>
</div><!-- closes iframe container -->
</div><!-- closes col 12-->
</div><!-- closes secondary row-->
</div><!-- closes col 6-->

<div class="col-md-6" >
#### Airport view
Total [ATFM delay](/definition/atfm-delay/) (arrival + departure) for main EUROCONTROL airports.
<div class="row align-items-start">
<div class="col-12">
<div id="apt-delay">
<iframe id="acc-delay-table" class="resp-iframe" src="https://www.eurocontrol.int/Economics/Oscar/plot-apt-delay-ranking-table.html" frameborder="0" style="border:0;" >
</iframe>
</div><!-- closes iframe container -->
</div><!-- closes col 12-->
</div><!-- closes secondary row-->
</div><!-- closes col 6-->
</div><!-- closes row -->
</div><!-- closes container -->
<br>
<a href="https://www.eurocontrol.int/Economics/Download/ACC_airport_delay.xlsx" class="btn btn-info" role="button" target="_blank">{{% dwnld_i %}} Download ACC/airport delay data</a>
<!-- </div><!-- closes tab pane-> -->
<!-- </div><!-- closes tab content-> -->


<!-- script for dly figures -->
<script type="text/javascript"> 
  <!-- code found @ https://stackoverflow.com/questions/9847580/how-to-detect-safari-chrome-ie-firefox-and-opera-browser -->
  var isFirefox = typeof InstallTrigger !== 'undefined';
  console.log("hello");
  var data

  if (isFirefox == true) {
   window.addEventListener('message', function (e) {
   var $iframe = $('#delay-plot');

   data = JSON.parse(e.data);
   console.log("hello again");
   UpdateDelay();
   
  }, false);
   console.log("hello3");

} else {
  window.onload = function() {
   window.addEventListener('message', function (e) {
   var $iframe = $('#delay-plot');

   data = JSON.parse(e.data);
   console.log("hello again");
   UpdateDelay();
   
  }, false);
   console.log("hello3");
  }
}
 function UpdateDelay() { 
     // Calculate datestrings
   var last_day = new Date(data.LAST_DATA_DAY);
   var last_day_text = last_day.toString();
       last_day_text = last_day_text.substring(8, 11) + last_day_text.substring(4, 8) + last_day_text.substring(11, 15);

 //calculate 1st day of rolling week and string
  var first_week_day = new Date();
      first_week_day = first_week_day.setDate(last_day.getDate()-6);
      first_week_day = new Date(first_week_day);
      first_week_day = first_week_day.toString();
  var last_week_text = first_week_day.substring(8, 11) + (last_day_text.substring(3, 7) == first_week_day.substring(4, 8) ? "" :  first_week_day.substring(4, 8)) + "- " + last_day_text;

  var y2d_day_text = last_day_text.substring(3, 7) == "Jan " ? "01 - " + last_day_text : "01 Jan - " + last_day_text;
  
// Calculate dly scorecard values
  var day_dly = data.DAY_DLY;
  var dif_day_prev_week = Math.round(data.DAY_DLY_PREV_WEEK_PERC*100);
      dif_day_prev_week = (dif_day_prev_week >= 0) ? "+" + dif_day_prev_week : "" + dif_day_prev_week ;

  var dif_day_2019 = Math.round(data.DAY_DLY_DIFF_2019_PERC*100);
      dif_day_2019 = (dif_day_2019 >= 0) ? "+" + dif_day_2019 : "" + dif_day_2019;

  var dif_day_prev_year = Math.round(data.DAY_DIFF_PREV_YEAR_PERC*100);
      dif_day_prev_year = (dif_day_prev_year >= 0) ? "+" + dif_day_prev_year : "" + dif_day_prev_year ;

  var week_dly= data.TOTAL_ROLLING_WEEK;
  var avg_week_dly = Math.round(week_dly/7);

  var dif_week_prev_week = Math.round(data.DIF_PREV_WEEK_PERC*100);
      dif_week_prev_week = (dif_week_prev_week >= 0) ? "+" + dif_week_prev_week : "" + dif_week_prev_week;
  
  var dif_week_2019 = Math.round(data.DIF_ROLLING_WEEK_2019_PERC*100);
      dif_week_2019 = (dif_week_2019 >= 0) ? "+" + dif_week_2019 : "" + dif_week_2019;
  
  var dif_week_prev_year = Math.round(data.DIF_WEEK_PREV_YEAR_PERC*100);
      dif_week_prev_year = (dif_week_prev_year >= 0) ? "+" + dif_week_prev_year : "" + dif_week_prev_year;
      
  var y2d_dly = data.Y2D_DLY_YEAR;
  var avg_y2d_dly = Math.round(data.Y2D_AVG_DLY_YEAR);
  var dif_y2d_2019 = Math.round(data.Y2D_DIFF_2019_PERC*100);
      dif_y2d_2019 = (dif_y2d_2019 >= 0) ? "+" + dif_y2d_2019 : "" + dif_y2d_2019;
  var dif_y2d_prev_year = Math.round(data.Y2D_DIFF_PREV_YEAR_PERC*100);
      dif_y2d_prev_year = (dif_y2d_prev_year >= 0) ? "+" + dif_y2d_prev_year : "" + dif_y2d_prev_year;

      
// Update scorecard values
  document.getElementById("last_day").innerHTML = "Day (" + last_day_text + ")";
  document.getElementById("last_week").innerHTML = "Rolling week (" + last_week_text + ")";
  document.getElementById("y2d_day_text").innerHTML = "Year to date (" + y2d_day_text + ")";

  document.getElementById("day_dly").innerHTML = String(day_dly).replace(/(.)(?=(\d{3})+$)/g, '$1,');
  document.getElementById("dif_day_prev_week").innerHTML = dif_day_prev_week + '%';
  document.getElementById("dif_day_2019").innerHTML = dif_day_2019 + '%';
  document.getElementById("dif_day_prev_year").innerHTML = dif_day_prev_year + '%';

  document.getElementById("week_dly").innerHTML = String(week_dly).replace(/(.)(?=(\d{3})+$)/g, '$1,');
  document.getElementById("avg_week_dly").innerHTML = String(avg_week_dly).replace(/(.)(?=(\d{3})+$)/g, '$1,') + " daily minutes";
  document.getElementById("dif_week_prev_week").innerHTML = dif_week_prev_week + '%';
  document.getElementById("dif_week_2019").innerHTML = dif_week_2019 + '%';
  document.getElementById("dif_week_prev_year").innerHTML = dif_week_prev_year + '%';

  document.getElementById("y2d_dly").innerHTML = String(y2d_dly).replace(/(.)(?=(\d{3})+$)/g, '$1,');
  document.getElementById("avg_y2d_dly").innerHTML = String(avg_y2d_dly).replace(/(.)(?=(\d{3})+$)/g, '$1,') + " daily minutes";
  document.getElementById("dif_y2d_2019").innerHTML = dif_y2d_2019 + '%';
  document.getElementById("dif_y2d_prev_year").innerHTML = dif_y2d_prev_year + '%';
 
}
</script>

