---
title: Daily Traffic Variation by State
date: '2020-04-16'
---

<style type="text/css">
.img-responsive {
    margin: 0 auto;
    max-width: 75%
}

.resp-container {
    position: relative;
    overflow: hidden;
    padding-top: 60.0%;
}

.resp-iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 150%;
    border: 0;
}
</style>
This dashboard shows the daily traffic variation[^1] for the main European Aircraft Operators compared to 2019[^2]. <br> 
Observed variations are the result of many different factors including: COVID-19, Overall economic downturn, Failure of airlines, ANSPs' disruptions,  Airports' disruptions, Traffic variation in 2019.
* The graphics on the top present the daily evolution, the average evolution of each week (starting on Mondays) and the moving average over the last 7 days.
* The bottom left graphic presents the breakdown of the Traffic[^3] variation for each ACC of the selected State.
* The bottom right graphic presents the breakdown of the Traffic[^4] variation for the main airports of the selected State

<div class="resp-container"><iframe class="resp-iframe" src="https://www.eurocontrol.int/Economics/DailyTrafficVariation-States.html" frameborder="0" style="border:0" allowfullscreen></iframe></div>

[^1]: Traffic at State level = Total IFR Flights (including international arrivals, departures and domestics).
[^2]: The comparison with the previous year is adjusted to fit the cosest comparable day: i.e. Monday 03/02/2020 is compared to Monday 04/02/2019.
[^3]: Traffic at ACC level = Total IFR Flights (including international arrivals, departures, domestics and overflights).
[^4]: Traffic at Airport level = Total Departing and Arriving IFR Flights from/to each airport.