---
title: "ANSPs individual factsheets"
output: html_document
---

```{r,  echo = FALSE, eval = TRUE, message=FALSE, warning=FALSE}
library(dplyr)
library(readxl)
library(jsonlite)

ansp <- read_xlsx(
  path  = here::here ("content","economics","ace_landing_page_data.xlsx"),
  sheet = "ANSP",
  range = cell_limits(c(1, 1), c(NA, NA))
  )%>%
  as_tibble()%>%
  toJSON() 

```



This page comprises factsheets for each ANSP participating to the ACE analysis. These factsheets are made of three pages which comprise the following information:

<div class="container-fluid">
<div class="row">
<div class="col-lg-6 pl-0 text-justify">
#### First page
The first page presents qualitative information about the institutional arrangements and corporate governance structure for each ANSP. This page also includes information relating to the scope of services provided by the ANSP, the number of ACC, APP and TWR operational units where it is responsible to provide ATC services, as well as a map of the area controlled by the ANSP. Finally, this page also shows high level financial and operational data for each organisation.

#### Second page
The second page displays an analysis of the historical development of the financial cost-effectiveness indicator and its main components over a five-year period. It examines the overall economic cost-effectiveness indicator and its two components (ATM/CNS costs per composite flight-hour, ATFM delay costs per composite flight-hour), and their evolution over the period (top left). It puts these in the context of the traffic growth observed in the ANSP’s airspace (top right). In this page, financial data are all expressed in real terms. 
Developments in the components of financial cost-effectiveness (ATCO-hour productivity, ATCO employment costs per ATCO-hour, and support costs per composite flight-hour) are also examined (middle left), to help identify the underlying causes of changes in overall cost-effectiveness. The charts on the middle right provide additional information in order to better understand the drivers behind the changes in the three components of financial cost-effectiveness.

#### Third page
The top charts of the third page present the financial cost-effectiveness indicator and its main components for individual ANSPs in comparison with their respective comparator group. The approach is to consider each ANSP in the context of a group of other ANSPs (comparators) which operate in relatively similar operational and economic environments. These comparator groups were determined for the purposes of the RP2 cost-efficiency target-setting process using a two-step approach combining the use of statistical tools (cluster analysis) with expert judgement. For a full description of the process, methodology and results see Annex I.C of the PRB report on RP2 EU-Wide Targets Ranges released in May 2013. Nine groups of comparators have been identified, some comprising a relatively large number of ANSPs and others only comprising two organisations.  Due to the unique nature of its airspace (upper airspace only, across four States), it was determined that Maastricht (MUAC) should be considered separately and therefore this ANSP was not included in the comparator group benchmarking analysis. Finally, two groups have been designed for the ANSPs not operating in SES States.

The chart on the top-left shows the level and changes in unit ATM/CNS provision costs over a five-year period for each ANSP part of the comparator group. The chart on the top-right shows for each ANSP the deviations in unit ATM/CNS provision costs, ATCO-hour productivity, employment costs per ATCO-hour and unit support costs from the average of the comparator group at the start and at the end of the period considered.

The chart in the middle of the third page shows the historical evolution of capital expenditure and depreciation, highlighting the ANSP’s investment cycles and their magnitude, across time. The ratio of these quantities is an indication of the rate at which the overall asset base is being expanded.

</div><!-- closes col -->
  
<div class="col-lg-6">
<div class="row">
<div class="col-8 float-left" id="ansp_list">
<label class="mb-0" for="ansp">Select ANSP:</label>
<select name="ansp" id="ansp" onchange="changeANSP(this.value)"></select>
</div>

<div class="col-4">
<a id="mydownload" href="/library/ace/ansp-factsheets/Albcontrol.pdf" role="button" target="_blank"
class="float-right pr-1 pl-1" style="padding-top:2px; padding-bottom:2px; color:black; border-radius:2px; border:1px solid #aaaaaa; background: linear-gradient(to bottom, #fcfcfc, #dddddd)" type="button" download>Download .pdf
</a>
</div>
</div><!-- closes row -->

<div>
<iframe id="MyEmbed_div" src="https://drive.google.com/viewerng/viewer?embedded=true&url=https://www.eurocontrol.int/ACE/ANSP-Factsheets/Albcontrol.pdf" width="100%" height="850pt">
</iframe>
</div>
</div><!-- closes col -->
</div><!-- closes row -->
</div><!-- closes container -->


<script id="json_ansp" type="application/json">`r ansp`</script>

<script type="text/javascript">
var data = document.getElementById("json_ansp").textContent
data = JSON.parse(data);

var myselect = document.getElementById("ansp")
var i = 0;

for (const val of data)
    {
        var option = document.createElement("option");
        option.value = data[i].ANSP_NAME;
        option.text = data[i].ANSP_NAME;
        myselect.appendChild(option);
        myselect.style.border="1px solid #aaaaaa";
        myselect.style.padding="2px";
        myselect.style.borderRadius="2px";
        myselect.style.background="linear-gradient(to bottom, #fcfcfc, #dddddd)";
        <!-- myselect.style.padding-bottom="2px"; -->
        <!-- console.log(data[i].ANSP_NAME); -->
        i = i+1;
    }

  document.getElementById("ansp_list").appendChild(label).appendChild(select);
  

</script>

<script type="text/javascript">

function changeANSP (value) {

		var element1 = document.getElementById("MyEmbed_div");
	  element1.src = 'https://drive.google.com/viewerng/viewer?embedded=true&url=https://www.eurocontrol.int/ACE/ANSP-Factsheets/'+value+'.pdf' ;

		var element2 = document.getElementById("mydownload");
		var myurl = '/library/ace/ansp-factsheets/'+value+'.pdf';
	  element2.setAttribute("href", myurl) ;
	  
	  element1.src = 'https://drive.google.com/viewerng/viewer?embedded=true&url=https://www.eurocontrol.int/ACE/ANSP-Factsheets/'+value+'.pdf' ;

}
</script>



