---
title: "About us"
---
```{r echo = FALSE, message = FALSE, warning = FALSE}
# run setup script
source(here::here("_common.R"))
```
Since its creation in 1998, the Performance Review Unit (PRU) has been responsible for monitoring and reviewing the performance of the European Air Traffic Management (ATM) System across a number of key performance areas and supports the independent [Performance Review Commission (PRC)](/about/prc/) in carrying out its tasks and work programme with the appropriate level of independence. 

The PRU is part of EUROCONTROL's Aviation Intelligence & Performance Review Unit which administratively reporting to the Directorate European Civil-Military Aviation (DECMA). 

The unit provides independent collection and validation of ANS performance-related data, intelligence gathering, performance analysis, ad-hoc reports and studies to contribute to performance improvements of European ANS. In performing its tasks, the PRU maintains transparent working arrangements with service providers, airspace user organisations and the industry.

In addition to the work carried out for the PRC within the [EUROCONTROL Performance Review System](https://www.eurocontrol.int/air-navigation-services-performance-review/), the PRU provides support to the European Commission (EC) in relation to the collection, validation, pre-analysis and provision of performance-related data for performance review in support of the [Single European Sky (SES)](/acronym/ses/) Performance and Charging Schemes.
The PRU also supports the official [Single European Sky (SES) Performance Dashboard][sesdash]. 

The [EUROCONTROL Performance Review System](https://www.eurocontrol.int/air-navigation-services-performance-review/) and the [SES](/acronym/ses/) Performance Scheme both contribute to improving the overall performance of air navigation services and network functions for general air traffic for the benefit of all aviation stakeholders, especially the travelling public, by applying the principles of complementarity, cooperation and synergy between them.

The [SES](/acronym/ses/) Performance Scheme provides the legislative/regulatory framework for setting targets for key performance indicators, assessing the respective performance plans of the [SES](/acronym/ses/) Member States/Functional Airspace Blocks and subsequently monitoring achieved performance against those.
The [EUROCONTROL Performance Review System](https://www.eurocontrol.int/air-navigation-services-performance-review/) complements the [SES](/acronym/ses/) Performance Scheme by providing the performance view on all the EUROCONTROL Member States and carrying out research and development into the longer-term evolution of ANS performance review including benchmarking with regions outside Europe. 


For feedback or questions please contact us at:
[Performance Review Unit](mailto:PRU-Support@eurocontrol.int)
(PRU-Support@eurocontrol.int).

[sesdash]: https://www.eurocontrol.int/prudata/dashboard/ "Single European Sky Performance Dashboard"