---
title: "Brazil"
---

Brazil and Europe represented by DECEA and EUROCONTROL engaged in 2016 in a cooperation agreement. Amongst other activities, this agreement entails the collaboration in developing in initial operational performance benchmarking exercise for Air Navigation Services (ANS).
Based on this agreement, DECEA started a Working Group, which has become the ATM Performance Indicators Management Committee, aiming at improving performance-based management. Through lessons learnt from the best practices observed at EUROCONTROL, and in particular PRU, DECEA established the Performance Section.

DECEA Performance Section and the PRU have established a joint project to foster the common understanding and harmonised interpretation of the proposed ICAO GANP indicators. The technical work has been conducted throughout the recent years comprising joint workshops and a series of web-based discussion sessions and face-to-face meetings. 
It also comprised the identification and validation of comparable data sources and joint data processing and analysis to produce this report.

<div class="col-sm-6">
<div class="container">
<div class="row">
<div class="card-deck">

```{r echo=FALSE}
blogdown::shortcode(
  "bootstrap-card-alt",
  img="x-cover-bra-eur-2019.png",
  link="bra-eur-2019/",
  title="7 December 2021",
  text="This report comprises two parts: a description of the operational performance in Brazil and Europe for the years 2016-2019; and a description of the regional system characteristics in terms of traffic/demand evolution during the COVID-19 pandemic crisis.", 
  alt="Comparison of Operational Air Navigation System Performance in Brazil and Europe 2016-2019", 
  command="Resize", 
  options="300x", 
  style="width: 18rem;", 
  class="mb-2"
  )


blogdown::shortcode(
  "bootstrap-card-alt",
  img="x-cover-bra-eur-2022.png",
  link="bra-eur/",
  title="28 October 2022",
  text="The second edition of the Brazil-Europe Comparison of Operational ANS performance covers the years 2019-2021. For the first time, it includes an estimate of additional fuel burn in the taxi phase.   ", 
  alt="Comparison of Operational Air Navigation System Performance in Brazil and Europe 2019-2022", 
  command="Resize", 
  options="300x", 
  style="width: 18rem;", 
  class="mb-2"
  )

```

</div>
</div>
</div>