---
title: Technical Notes - Composite Risk Index (CRI)
type: "Safety"
date: '2021-01-22'
tags:
  - News
  - Funding
---

**News**: [Updated CRI methodology now available][cri]<br> 

In 2019, the PRC published its concept of the Composite Risk Index (CRI) as an innovative option to measure the safety performance of the European ATM system. 

All safety programmes desire accurate safety risk quantification in order to provide a meaningful expression of risk. As there are typically multiple safety risks associated with a system or event, the quantification of the total safety risk is a major challenge.

One possible way to define the total safety risk is the concept of a Composite Risk Index (CRI) which aims at measuring the performance of ATM system as a whole and/or its individual entities (service providers or Member States). The proposed CRI methodology presents a cumulative risk value, calculated by aggregating all reported, assessed and severity classified safety-related incidents which also takes the human perception of the equivalent risk into account.

The CRI methodology was now improved to better take account of local specific operating conditions, airspace size, and complexity.

<a href="/publications/studies/2021_01_22_tn_cri" class="btn btn-primary" role="button"> Learn more </a>


[cri]: /publications/studies/2021_01_22_tn_cri "Composite Risk Index Methodology"