---
title: All Pre-Departure Delay (all delay causes) Dataset
bibliography: ["../../../static/bib/aviation.bib"]
link-citations: true
slug: all-pre-departure-delay
---
```{r echo = FALSE, message = FALSE, warning = FALSE}
# run setup script
source(here::here("_common.R"))
```

## Data description

The average pre-departure delay per departure for all delay causes.

## Column naming and types

| Column name   | Data Source      | Label                         | Description                                                                | Example      |
|---------------|------------------|-------------------------------|----------------------------------------------------------------------------|--------------|
| YEAR          | Network Manager  | YEAR                          | Reference year                                                             | 2014         |
| MONTH_NUM     | Network Manager  | MONTH_NUM                     | Month (numeric)                                                            | 01           |
| MONTH_MON     | Network Manager  | MONTH_MON                     | Month (3-letter code)                                                      | JAN          |
| FLT_DATE      | Network Manager  | FLT_DATE                      | Date of flight                                                             | 01-Jan-2014  |
| APT_ICAO      | Network Manager  | APT_ICAO                      | ICAO 4-letter airport designator                                           | EDDK         |
| APT_NAME      | PRU              | APT_NAME                      | Airport name                                                               | Cologne-Bonn |
| STATE_NAME    | PRU              | STATE_NAME                    | Name of the State in which the airport is located                          | Germany      |
| FLT_DEP_1     | Network Manager  | IFR departures - (NM)         | Number of IFR departures from Network Manager                              | 66           |
| FLT_DEP_IFR_2 | Airport Operator | IFR departures - (APT)        | Number of IFR departures for which data was submitted by airport operators | 66           |
| DLY_All_PRE_2 | Airport Operator | All causes pre-departure delay (APT) | Minutes of pre-departure delay (all causes)                                 | 0            |
## References

