---
layout: default
title: Financial Dashboard Guide
output:
  blogdown::html_page:
    toc: true
---
<style>
span.mjx-chtml.MJXc-display {
/* text-align: left !important; */
}
</style>
## Overview

The objective of the dashboard is to create an online resource of ANSPs’ financial information and indicators with interactive features, which is accessible and allows for comparisons over time.

All information presented has been collected from ANSPs’ publicly available financial statements, where the financial information corresponds to the legal reporting entity as a whole and, therefore, in some cases differs from the data reported in the [ACE Benchmarking Reports](https://www.eurocontrol.int/ACE/ACE-Home.html).

Financial information has been collected for the years 2017 to 2020, and the intention is to continue collecting data annually following the publication of annual financial statements. The objective of this dashboard is, as far as possible, to reflect the information as provided in each ANSP’s income statement, balance sheet and cash flow statement. The data presented was validated with each participating ANSP prior to publication


## Dashboard

At the top of the dashboard, users can select the ANSP and year for which data is displayed. All information and data displayed within the dashboard relates to the selected ANSP, and where a single year’s data is shown within a chart or figure, the data relates to the selected year. All time series figures and charts show data from 2017 to 2020 and are not altered by the selected year.

The top section of the dashboard provides an overview of the selected ANSP, including information on:

* the organisational and corporate arrangements;
* the additional scope of activities, in addition to the provision of ATC services to GAT; and
* the average share of the ANSP’s revenue as a proportion of total revenue across all ANSPs in the Pan-European System over the period shown in the dashboard. 

The remainder of this section describes the three main sections of the dashboard. Unless otherwise stated, figures are expressed in national currencies and in nominal prices.


### Income Statement section
Income statements report information on a company revenues and expenses throughout a year. The format of the income statements can vary across different ANSPs, in terms of which items are reported, the level of detail provided and where items are reported within the income statement.

The figures presented in the dashboard are based only on what is presented in ANSPs’ respective audited income statements (i.e. not incorporating the additional information or the level of disaggregation disclosed as part of the notes on financial statements) except in cases where depreciation and amortisation expenses are not reported in the income statement.


### Income statement items


Revenue
:  Income generated from normal business operations.
   Common items include operating income, other operating income and grants.
    
Opex (Operating expenditure)
:  Expenses generated from normal business operations.
   Common items include staff (wages and salaries, employers' contributions to
   social security and pensions, etc.) and non-staff operating costs
   (such as services, materials, maintenance, etc.).
   It does not include Depreciation Amortisation and Other non-cash Items (defined below).

Depreciation and amortisation
:  Accounting expenses (which do not involve a cash payment) representing either,
   the cost of tangible assets (depreciation) or the lowering of the value of
   intangible assets (amortisation), spread over their useful life or a set period.
   Note that for ANSPs applying IFR16, leased assets incur depreciation costs. 

Other non-cash items
:  The net total of income and expenses (except depreciation and amortisation)
   that do not involve a cash payment.
   Common items include capitalised costs, impairment and disposal of capital
   assets, and provisions for expenses (and/or reversals of these).

Net financial income/expense
:  The net total of income and expenses from financing activities (including
   investments and borrowing) and the change in value of financial assets.
   Common items include interest income and expenses, gains and losses on
   foreign currency transactions, and gains and losses on financial assets. 

Other income/expense[^1]
:  The net total of income and expenses generated from sources not directly
   related to normal business operations.
   Common items include income from joint ventures and subsidiaries and,
   exceptional income and expenses.

[^1]: Not currently shown in DB but is used to calculated the pre-tax profit.


### Income statement profitability measures and ratios

EBITDA
:  Profitability measure representing earnings generated from normal business
   operations, that is, before accounting for interest, taxes, amortisation and
   other non-cash items.
   A higher EBITDA value implies a higher level of profitability from normal
   operations (a negative value implies a loss).<br>
   $$\mathrm{EBITDA} = \mathrm{Revenue} - \mathrm{Opex}$$
   
   
Operating income (EBIT)
:  Profitability measure representing earnings generated from operations,
   before deduction of interest and taxes. A higher EBIT value implies a higher
   level of profitability from operations after accounting for depreciation,
   amortisation and other non-cash items (a negative value implies a loss).<br>
   $$\mathrm{EBIT} = \mathrm{Revenue} - \mathrm{Opex} - \mathrm{Depreciation\ Amortisation} - \mathrm{Other\ NonCash\ Items}$$

Pre-tax profit
:  Profitability measure representing earnings generated from operations,
   after accounting for all (pre-tax) income and expenses.
   A higher pre-tax profit value implies a higher level of profitability
   (a negative value implies a loss).<br>
   $$\mathrm{Pre\textrm{-}tax\ profit} = \mathrm{Revenue}-\mathrm{Opex}-\mathrm{Depreciation\ \& \ Amortisation} - \mathrm{Other\ NonCash\ Items} - \frac{\mathrm{Net\ Financial\ Income}}{\mathrm{Expense}} - \frac{\mathrm{Other\ Income}}{\mathrm{Expense}}$$
 
EBITDA margin %
:  Profitability ratio showing EBITDA as a proportion of revenue.<br>
   $$\mathrm{EBITDA\ margin\ \%} = \frac{\mathrm{EBITDA}}{\mathrm{Revenue}}$$
   


### Balance Sheet Section

Balance sheets report on a company assets, liabilities and shareholders’ equity at the end of the calendar year (except for NATS, which has financial years running from 1 April to 31 March the following year). The format of the balance sheets across ANSPs’ financial statements is relatively standardised, though some variation remains in terms of how some items are reported.

The figures presented in the dashboard are based only on what is presented in ANSPs’ balance sheets (i.e. not incorporating additional information or the level of disaggregation disclosed as part of the notes on financial statements).

#### Balance sheet items

Cash and equivalents
:	 Component of current assets that represents assets that are cash or can be
   converted into cash immediately.

Current assets
:	 All the assets of a company that are expected to be conveniently sold,
   consumed, used, or exhausted through standard business operations within
   the accounting year.
   Common items include cash and equivalents, accounts receivable, short-term
   investments and pre-paid expense

Non-current assets
:  A company's long-term investments for which the full value will not be
  realised within the accounting year.
  They are generally highly illiquid, meaning these assets cannot easily be
  converted into cash.
  Common items include tangible fixed assets, intangible fixed assets
  (including, right of use for those applying IFRS 16) and long-term investments.
  (Also includes accrued and deferred charges, and assets held for sale,
  where not reported as of current assets or non-current assets).

Total assets
:  Combined total of current assets and non-current assets.

Current liabilities
:  Financial obligations that are due to be paid within the accounting year.
   Common items include accounts payable, short-term debt and short-term lease obligations. 

Non-current liabilities
:  Financial obligations that become due beyond the accounting year.
   Common items include long-term debt, long-term lease obligations and
   pension benefit obligations.
   (Also includes accrued and deferred charges, and provisions,
   where not reported as of current liabilities or non-current liabilities).

Shareholders’ equity
:  Owners’ invested funds equivalent to the value to company net worth or
   the residual claim on assets after liabilities have been paid.

Total liabilities & equity
:  Combined total of current liabilities, non-current liabilities and
   shareholders’ equity.


#### Balance sheet ratios

Equity ratio
:  The ratio of shareholders equity to total liabilities & equity.
   This ratio indicates the extent of financial leverage, that is, to what
   extent assets are funded using equity versus debt.
   A ratio above 0.5 indicates a higher share of equity and
   a ratio below 0.5 indicates a higher share of debt.<br>
   $$\mathrm{Equity\ ratio} = \frac{\mathrm{Shareholders\ Equity} }{ \mathrm{Total\ Liabilities\ \&\ Equity}}$$

Current ratio
:  The ratio of current assets to current liabilities.
   Liquidity ratio that measures a company's ability to pay short-term obligations.
   A ratio a above 1 indicates current assets are larger than current liabilities,
   and a higher figure indicates a greater level of liquidity.<br>
   $$\mathrm{Current\ ratio} = \frac{\mathrm{Current\ Assets}}{\mathrm{Current\ Liabilites}}$$

Cash on hand days
:  The numbers of days of opex that can be paid for using cash and equivalents
   reserves. Liquidity measure that measures the number of days opex can be
   paid using only cash reserves, assuming no revenue.
   A higher figure indicates a high level of cash reserves, relative to opex.<br>
   $$\mathrm{Cash\ on\ hand\ days} = 365 \times \frac{\mathrm{Cash\ \&\ Equivalents}}{\mathrm{Opex}}$$


### Cash Flow Statement Section

Cash flow statements report cash inflows and outflows throughout the year. The format of cash flow statements, across ANSPs’ financial statements, is relatively standardised, though there is some variation in terms of how items are reported. It should be noted that not all ANSPs’ financial statements include cash flow statements; therefore, no information provided for these organisations in this section of the dashboard.

The figures presented in the dashboard are based only on what is presented in ANSPs’ cash flow statements (i.e. not incorporating additional information or the level of disaggregation disclosed as part of the notes on financial statements) except in cases where the capex is not reported in the cash flow statement.

#### Cash flow statement items

Net cash flow from operating activities
:  The net total of cash inflows and outflows generated from normal business operations.

Net cash flow from investing activities
:  The net total of cash inflows and outflows generated from investment,
   including capital expenditure and cash flows arising from the sale or
   acquisition of tangible, intangible or financial assets.

Capex (Capital expenditure)
:  A component of cash flow from investing activities that represents the funds
   used to acquire capital non-current assets.

Net cash flow from financing activities
:  The net total of cash inflows and outflows used to fund the company,
   including debt, equity and dividend transactions.

Net cash flow
:  The net total of cash flow from operating activities, cash flow from
   investing activities and cash flow from financing activities. 


#### Cash flow statement cash measures

Free cash flow
:  Representation of cash generated after accounting for outflows to support
   operations and maintain capital assets.
   A higher figure indicates a higher level of cash generated.
   $$\mathrm{Free\ cash\ flow} = \mathrm{Net\ Cash\ flow\ from\ Operating\ Activities} - \mathrm{Capex} $$

Cash flow from operating activities (as % of revenue)
:  Cash flow ratio showing cash flow from operating activities as a proportion
   of revenue.
   A higher negative value indicates a higher level of outflows, and
   a higher positive value indicates a higher level of cash inflows,
   relative to revenue.
   $$\mathrm{Cash\ flow\ from\ operating\ activities\ (\%\ of\ revenue)} = \frac{\mathrm{Net\ cash\ flow\ from\ Pperating Activities}}{\mathrm{Revenue}}$$
Cash flow from investing activities (as % of revenue)
:  Ratio showing net cash flow from investing activities relative to revenue,
   as a measure for the overall size of operations.
   A higher negative value indicates a higher level of outflows, and
   a higher positive value indicates a higher level of cash inflows,
   relative to revenue.
   $$\mathrm{Cash\ flow\ from\ investing\ activities\ (\%\ of\ revenue)} = \frac{\mathrm{Net\ cash\ flow\ from\ investing activities}}{\mathrm{Revenue}}$$
   
Cash flow from financing activities (as % of revenue)
:  Ratio showing the net cash flow financing activities relative to revenue,
   as a measure for the overall size of operations.
   A higher negative value indicates a higher level of outflows, and 
   a higher positive value indicates a higher level of cash inflows,
   relative to revenue.
   $$\mathrm{Cash\ flow\ from\ financing\ activities\ (\%\ of\ revenue)} = \frac{\mathrm{Net\ cash\ flow\ from\ financing\ activities}}{\mathrm{Revenue}}$$

Net cash flow (as % of revenue)
:  Ratio showing net cash flow relative to revenue, as a measure for the
   overall size of operations.
   A higher negative value indicates a higher level of outflows, and
   a higher positive value indicates a higher level of cash inflows,
   relative to revenue.
   $$\mathrm{Net\ cash\ flow\ (\%\ of\ revenue)} = \frac{\mathrm{Net\ cash\ flow}}{\mathrm{Revenue}}$$
